[package]
name = "ruget-package-spec"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
ruget-common = { path = "../ruget-common" }
ruget-semver = { path = "../ruget-semver" }

url = "2.1.0"
nom = "6.0.0"
percent-encoding = "2.1.0"
bytecount = "0.6.0"
