[package]
name = "turron-dotnet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turron-common = { path = "../turron-common" }
dotnet-semver = { path = "../dotnet-semver" }

which = "4.2.2"
