[package]
name = "thisdiagnostic"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
thiserror = "1.0.22"
colored = "2.0.0"
thisdiagnostic-derive = { path = "../thisdiagnostic-derive" }
