[package]
name = "ruget-command"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
thisdiagnostic = { version = "0.1.0", path = "../../../thisdiagnostic" }

async-trait = "0.1.19"
