[package]
name = "ruget-command"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
async-trait = "0.1.19"
# miette = "0.2.0"
miette = { path = "../../../miette" }
