[package]
name = "miette-utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# miette = "0.2.1"
miette = { path = "../../../miette" }
thiserror = "1.0.26"
