[package]
name = "turron-pick-version"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
turron-common = { path = "../turron-common" }
dotnet-semver = {path = "../dotnet-semver" }
